#########################################################################################
# Template for project Flow123d
#########################################################################################

# TODO for some reason including both files at once causes problem, each file seperatedly
# included works fine


# defaults values
- defaults:
    name: flow123d-build
    node: "{platform}"
    workspace: "F123-{platform}-{build-type}"
    # TODO log rotate 200 days
    wrappers:
      - build-name:
          name:  "${{PROPFILE,file=\"prop.file\",property=\"BUILD_NAME\"}}  #${{BUILD_NUMBER}}"



# --------------------------------------------------------------- DAILY UPDATE
- job:          !include misc/daily-update.yaml
# --------------------------------------------------------------- COVERAGE
- job:          !include misc/coverage.yaml



# --------------------------------------------------------------- START IMAGE
- job-template: !include debug/start-image.yaml
- job-template: !include release/start-image.yaml


# --------------------------------------------------------------- CONFIGURE
- job-template: !include common/configure.yaml
# --------------------------------------------------------------- BUILD
- job-template: !include common/build.yaml
# --------------------------------------------------------------- UNIT-TESTS
- job-template: !include common/unit-tests.yaml
# --------------------------------------------------------------- INT-TESTS
- job-template: !include common/int-tests.yaml
# --------------------------------------------------------------- MAKE DOC
- job-template: !include common/make-doc.yaml
# --------------------------------------------------------------- PACKAGE
- job-template: !include common/package.yaml


# --------------------------------------------------------------- STOP IMAGE
- job-template: !include common/stop-image.yaml



# --------------------------------------------------------------- MULTIJOB
- job-template: !include debug/multijob.yaml
- job-template: !include release/multijob.yaml

# --------------------------------------------------------------- PROJECT
- project:      !include release/project.yaml
- project:      !include debug/project.yaml
