#########################################################################################
# Template for project Flow123d
#########################################################################################

# TODO for some reason including both files at once causes problem, each file seperatedly 
# included works fine


# defaults values
- defaults:
    name: flow123d-build
    node: "{platform}"
    workspace: "F123-{platform}-{build-type}"
    # TODO log rotate 200 days
    wrappers:
      - build-name:
          name:  "${{PROPFILE,file=\"prop.file\",property=\"BUILD_NAME\"}}  #${{BUILD_NUMBER}}"



#########################################################################################
# Daily docker image update and reference repo update
#########################################################################################

- job:
    name: Flow123d-daily-update
    description: 'Daily maintenance update'
    node: ci2runner
    workspace: F123-ci2runner
    wrappers:
      - build-name:
          name:  "daily-update #${BUILD_NUMBER}"
    triggers:
      - timed: "H 1 * * *" # run this job every day at 1AM
    builders:
      - shell: |
          # update reference repo
          cd /home/builder/git-cache/flow123d.git
          git branch -vv
          git log -n 20 --oneline --graph
          git fetch --all --prune
          
          # update images
          cd /home/builder/git-cache/
          rm -rf flow123d
          git clone --reference /home/builder/git-cache/flow123d.git https://github.com/flow123d/flow123d.git
          flow123d/bin/fterm update
          flow123d/bin/fterm build
          YES_TO_ALL=1 flow123d/bin/fterm remove-old
          docker images
          docker ps -a
          
          
          

#########################################################################################
# Template for project Flow123d - DEVELOPER BUILDS
#########################################################################################

- project:
    name: "Multijob project debug"
    platform: ci2runner
    build-type: debug
    unit-dir:
      - $PLACEHOLDER_unit_list$
    test-dir:
      - $PLACEHOLDER_test_list$
    jobs:
      - "Flow123d-{platform}-{build-type}-configure"
      - "Flow123d-{platform}-{build-type}-build"
      - "Flow123d-{platform}-{build-type}-unit-test-{unit-dir}"
      - "Flow123d-{platform}-{build-type}-test-{test-dir}"
      - "Flow123d-{platform}-{build-type}-make-doc"
      - "Flow123d-{platform}-{build-type}-stop-image"
      - "Flow123d-{platform}-debug-start-image"
      - "Flow123d-{platform}-debug-multijob"


# ---------------------------------------------------------------------------- #
# ---------- START IMAGE ----------------------------------------------------- #
# ---------------------------------------------------------------------------- #
- job-template:
   name: "Flow123d-{platform}-debug-start-image"
   display-name: "{build-type} / Flow123d start image"
   defaults: flow123d-build
   builders:
     - inject:
         properties-file: prop.file
     - shell: |
         docker rm -f cont{build-type} || echo "container not running"
         flow123d/bin/fterm -v dbg -- --privileged -di --name cont{build-type} -v /home/builder/git-cache/flow123d.git:/home/builder/git-cache/flow123d.git
         echo "FLOW=/opt/flow123d/flow123d" >> prop.file

# ---------------------------------------------------------------------------- #
# ---------- START IMAGE ----------------------------------------------------- #
# ---------------------------------------------------------------------------- #
- job-template:
    name: "Flow123d-{platform}-release-start-image"
    display-name: "{build-type} / Flow123d start image"
    defaults: flow123d-build
    builders:
      - inject:
          properties-file: prop.file
      - shell: |
          docker rm -f cont{build-type} || echo "container not running"
          flow123d/bin/fterm -v rel -- --privileged -di --name cont{build-type} -v /home/builder/git-cache/flow123d.git:/home/builder/git-cache/flow123d.git
          echo "FLOW=/opt/flow123d/flow123d"                >> prop.file
          echo "PACK_NAME=Flow123d-2.0.0-Linux.tar.gz"      >> prop.file
          echo "PACK_PATH=./Flow123d-2.0.0-Linux.tar.gz"    >> prop.file



# ---------------------------------------------------------------------------- #
# ---------- CONFIGURE ------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
- job-template:
    name: "Flow123d-{platform}-{build-type}-configure"
    display-name: "{build-type} / Flow123d configure"
    defaults: flow123d-build
    builders:
      - inject:
          properties-file: prop.file
      - shell: |
          docker exec cont{build-type} git clone --reference /home/builder/git-cache/flow123d.git -b ${{_GIT_BRANCH}} https://github.com/flow123d/flow123d.git ${{FLOW}}
          docker exec cont{build-type} cp ${{FLOW}}/config/config-jenkins-docker-{build-type}.cmake ${{FLOW}}/config.cmake
          docker exec cont{build-type} make -C ${{FLOW}} cmake


# ---------------------------------------------------------------------------- #
# ---------- BUILD ----------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
- job-template:
    name: "Flow123d-{platform}-{build-type}-build"
    display-name: "{build-type} / Flow123d build"
    defaults: flow123d-build
    builders:
      - inject:
          properties-file: prop.file
      - shell: |
          docker exec cont{build-type} make -C ${{FLOW}} -j4 all
          docker exec cont{build-type} make -C ${{FLOW}}/build_tree/unit_tests -j4 gtest_mpi_obj 


# ---------------------------------------------------------------------------- #
# ---------- UNIT-TESTS ------------------------------------------------------ #
# ---------------------------------------------------------------------------- #
- job-template:
    name: "Flow123d-{platform}-{build-type}-unit-test-{unit-dir}"
    display-name: "{build-type} / Flow123d unit-test {unit-dir}"
    defaults: flow123d-build
    disabled: false
    builders:
      - inject:
          properties-file: prop.file
      - shell: |
          echo  ${{RUN_UNIT_TESTS}}
          $(exit ${{RUN_UNIT_TESTS}}) || docker exec cont{build-type} make -C ${{FLOW}}/build_tree/unit_tests/{unit-dir} -k all-test


# ---------------------------------------------------------------------------- #
# ---------- INT-TESTS ------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
- job-template:
    name: "Flow123d-{platform}-{build-type}-test-{test-dir}"
    display-name: "{build-type} / Flow123d int-test {test-dir}"
    defaults: flow123d-build
    disabled: false
    builders:
      - inject:
          properties-file: prop.file
      # Following is a hack how to run just serial tests in a branch which contains file 'tests/run_serial_only'.
      - shell: |
          echo  ${{RUN_INTEGRATION_TESTS}}
          if -f ${{FLOW}}/tests/run_serial_only
          then
                $(exit ${{RUN_INTEGRATION_TESTS}}) || docker exec cont{build-type} ${{FLOW}}/tests/runtest ${{FLOW}}/tests/{test-dir} -n 1 --keep-going --batch
          else      
                $(exit ${{RUN_INTEGRATION_TESTS}}) || docker exec cont{build-type} ${{FLOW}}/tests/runtest ${{FLOW}}/tests/{test-dir} --keep-going --batch
          fi      
            
                

# ---------------------------------------------------------------------------- #
# ---------- STOP IMAGE ------------------------------------------------------ #
# ---------------------------------------------------------------------------- #
- job-template:
    name: "Flow123d-{platform}-{build-type}-stop-image"
    display-name: "{build-type} / Flow123d stop image"
    defaults: flow123d-build
    builders:
      - inject:
          properties-file: prop.file
      - shell: |
          docker rm -f cont{build-type}


# ---------------------------------------------------------------------------- #
# ---------- MULTIJOB -------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
- job-template:
    name: "Flow123d-{platform}-debug-multijob"
    display-name: "debug / Flow123d multijob"
    project-type: multijob
    defaults: flow123d-build
    properties:
      - raw:
          xml: |
            <hudson.model.ParametersDefinitionProperty>
              <parameterDefinitions>
                <hudson.model.StringParameterDefinition>
                  <name>BRANCH_NAME</name>
                  <description>Specify branch name you want to build. Default value will build master branch.</description>
                  <defaultValue>$GIT_BRANCH</defaultValue>
                </hudson.model.StringParameterDefinition>
                <hudson.model.StringParameterDefinition>
                  <name>RUN_UNIT_TESTS</name>
                  <description>If set to '0' will not run any unit-test.</description>
                  <defaultValue>1</defaultValue>
                </hudson.model.StringParameterDefinition>
                <hudson.model.StringParameterDefinition>
                  <name>RUN_INTEGRATION_TESTS</name>
                  <description>If set to '0' will not run any integration tests.</description>
                  <defaultValue>1</defaultValue>
                </hudson.model.StringParameterDefinition>
              </parameterDefinitions>
            </hudson.model.ParametersDefinitionProperty>
    block-downstream: yes
    scm:
      - git:
          url: https://github.com/flow123d/flow123d.git
          reference-repo: /home/builder/git-cache/flow123d.git
          branches:
              - "*"
          basedir: flow123d
          browser: githubweb
          browser-url: https://github.com/flow123d/flow123d/
          skip-tag: true

    wrappers:
      - inject:
          script-content: |
            rm -f prop.file && touch prop.file
            echo "RUN_UNIT_TESTS=1" >> prop.file
            echo "RUN_INTEGRATION_TESTS=1" >> prop.file 
            echo "BUILD_NAME=${{BRANCH_NAME#origin/}}@${{GIT_COMMIT:0:6}}" >> prop.file
            echo "_GIT_BRANCH=${{BRANCH_NAME#origin/}}"                    >> prop.file
            
      - build-name:
          name:  "${{PROPFILE,file=\"prop.file\",property=\"_GIT_BRANCH\"}}@${{GIT_REVISION, length=6}} #${{BUILD_NUMBER}}"

    triggers:
      - github

    builders:
      - multijob:
          name: "Start image"
          condition: SUCCESSFUL
          projects:
            - name: "Flow123d-{platform}-debug-start-image"
      # ---------- START IMAGE ----------------------------------------------- #
      - multijob:
          name: "Configure flow123d Phase"
          condition: SUCCESSFUL
          projects:
            - name: "Flow123d-{platform}-debug-configure"

      - multijob:
          name: "Build flow123d Phase"
          condition: SUCCESSFUL
          projects:
            - name: "Flow123d-{platform}-debug-build"

      - multijob:
          name: "Unit tests"
          condition: COMPLETED
          projects:
            - name: "Flow123d-{platform}-debug-unit-test-$PLACEHOLDER_unit_list$"

      - multijob:
          name: "Integration tests"
          condition: COMPLETED
          projects:
            - name: "Flow123d-{platform}-debug-test-$PLACEHOLDER_test_list$"
              kill-phase-on: NEVER
      - multijob:
          name: "Make doc"
          condition: COMPLETED
          projects:
            - name: "Flow123d-{platform}-debug-make-doc"
      # ---------- STOP IMAGE ------------------------------------------------ #
      - multijob:
          name: "Stop image"
          condition: SUCCESSFUL
          projects:
            - name: "Flow123d-{platform}-debug-stop-image"



#########################################################################################
# Template for project Flow123d - RELEASE BUILDS
#########################################################################################


- project:
    name: "Multijob project release"
    platform: ci2runner
    build-type: release
    unit-dir:
      - $PLACEHOLDER_unit_list$
    test-dir:
      - $PLACEHOLDER_test_list$
    jobs:
      - "Flow123d-{platform}-{build-type}-configure"
      - "Flow123d-{platform}-{build-type}-build"
      - "Flow123d-{platform}-{build-type}-unit-test-{unit-dir}"
      - "Flow123d-{platform}-{build-type}-test-{test-dir}"
      - "Flow123d-{platform}-{build-type}-make-doc"
      - "Flow123d-{platform}-{build-type}-package"
      - "Flow123d-{platform}-{build-type}-stop-image"
      - "Flow123d-{platform}-release-start-image"
      - "Flow123d-{platform}-release-multijob"





# ---------------------------------------------------------------------------- #
# ---------- MAKE DOC -------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
- job-template:
    name: "Flow123d-{platform}-{build-type}-make-doc"
    display-name: "{build-type} / Flow123d make doc"
    defaults: flow123d-build
    builders:
      - inject:
          properties-file: prop.file
      - shell: |
          docker exec cont{build-type} make -C ${{FLOW}} FORCE_DOC_UPDATE=1 ref-doc
          docker exec cont{build-type} make -C ${{FLOW}} html-doc
          docker exec cont{build-type} make -C ${{FLOW}} doxy-doc
          


# ---------------------------------------------------------------------------- #
# ---------- PACKAGE --------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
- job-template:
    name: "Flow123d-{platform}-{build-type}-package"
    display-name: "{build-type} / Flow123d package"
    defaults: flow123d-build
    builders:
      - inject:
          properties-file: prop.file
      - shell: |
          destination=$(pwd)/publish

          rm -rf publish && mkdir -p publish
          git clone https://github.com/janhybs/flow123d-package.git

          make -C flow123d-package \
                  destination=$destination \
                  all

          make -C flow123d-package \
                  destination=$destination \
                  remove-unwanted

          make -C flow123d-package \
                  push-to-hub

          ls -la $destination

    publishers:
      - cifs: 
          site: 'flow123d@intec'
          target: '/docker-images/${{DOCKER_IMAGE_NAME}}/'
          source: publish/**/*
          remove-prefix: publish/



# ---------------------------------------------------------------------------- #
# ---------- MULTIJOB -------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
- job-template:
    name: "Flow123d-{platform}-release-multijob"
    display-name: "release / Flow123d multijob"
    project-type: multijob
    defaults: flow123d-build
    properties:
      - raw:
          xml: |
            <hudson.model.ParametersDefinitionProperty>
              <parameterDefinitions>
                <hudson.model.StringParameterDefinition>
                  <name>BRANCH_NAME</name>
                  <description>Specify branch name you want to build. Default value will build master branch.</description>
                  <defaultValue>$GIT_BRANCH</defaultValue>
                </hudson.model.StringParameterDefinition>
                <hudson.model.StringParameterDefinition>
                  <name>RUN_UNIT_TESTS</name>
                  <description>If set to '0' will not run any unit-test.</description>
                  <defaultValue>1</defaultValue>
                </hudson.model.StringParameterDefinition>
                <hudson.model.StringParameterDefinition>
                  <name>RUN_INTEGRATION_TESTS</name>
                  <description>If set to '0' will not run any integration tests.</description>
                  <defaultValue>1</defaultValue>
                </hudson.model.StringParameterDefinition>
              </parameterDefinitions>
            </hudson.model.ParametersDefinitionProperty>
    block-downstream: yes
    scm:
      - git:
          url: https://github.com/flow123d/flow123d.git
          reference-repo: /home/builder/git-cache/flow123d.git
          branches:
              - master
              - 2.1.0
              - 2.1.2
              - 2.2.0
              - 3.0.0_dev
          basedir: flow123d
          browser: githubweb
          browser-url: https://github.com/flow123d/flow123d/
          skip-tag: true

    wrappers:
      - inject:
          script-content: |
            rm -f prop.file && touch prop.file
            echo "RUN_UNIT_TESTS=1" >> prop.file
            echo "RUN_INTEGRATION_TESTS=1" >> prop.file 
            echo "BUILD_NAME=${{BRANCH_NAME#origin/}}@${{GIT_COMMIT:0:6}}"          >> prop.file
            echo "DOCKER_IMAGE_NAME=${{BRANCH_NAME#origin/}}-${{GIT_COMMIT:0:6}}"   >> prop.file
            echo "_GIT_BRANCH=${{BRANCH_NAME#origin/}}"                             >> prop.file
            
      - build-name:
          name:  "${{PROPFILE,file=\"prop.file\",property=\"_GIT_BRANCH\"}}@${{GIT_REVISION, length=6}} #${{BUILD_NUMBER}}"

    triggers:
      - github

    builders:
      - multijob:
          name: "Start image"
          condition: SUCCESSFUL
          projects:
            - name: "Flow123d-{platform}-release-start-image"
      - multijob:
          name: "Configure flow123d Phase"
          condition: COMPLETED
          projects:
            - name: "Flow123d-{platform}-release-configure"

      - multijob:
          name: "Build flow123d Phase"
          condition: COMPLETED
          projects:
            - name: "Flow123d-{platform}-release-build"
      - multijob:
          name: "Unit tests"
          condition: COMPLETED
          projects:
            - name: "Flow123d-{platform}-release-unit-test-$PLACEHOLDER_unit_list$"
      - multijob:
          name: "Integration tests"
          condition: COMPLETED
          projects:
            - name: "Flow123d-{platform}-release-test-$PLACEHOLDER_test_list$"
              kill-phase-on: NEVER
      - multijob:
          name: "Make doc"
          condition: COMPLETED
          projects:
            - name: "Flow123d-{platform}-release-make-doc"
      - multijob:
          name: "Package"
          condition: COMPLETED
          projects:
            - name: "Flow123d-{platform}-release-package"
      - multijob:
          name: "Stop image"
          condition: COMPLETED
          projects:
            - name: "Flow123d-{platform}-release-stop-image"
