common_config:
  proc: [1, 2]
  memory_limit: 1000

test_cases:
- file: 01_vtk.yaml
- file: 02_dg_dp.yaml
- file: 03_dg_dp_sorp_small_output_multi_fields.yaml
- file: 04_dg_dp_sorp_small.yaml
- file: 05_y_branch.yaml
- file: 06_diffusion_fracture.yaml
