# ---------------------------------------------------------------------------- #
# ---------- COVERAGE -------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
name: Flow123d-coverage
description: |
  Coverage report available at
  <a href="https://coveralls.io/github/flow123d/flow123d">coveralls.io</a>
node: ci2runner
workspace: F123-ci2runner
wrappers:
  - build-name:
      name:  "coverage-report #${BUILD_NUMBER}"
scm:
  - git:
      url: https://github.com/flow123d/flow123d.git
      reference-repo: /home/builder/git-cache/flow123d.git
      branches:
          - master
      basedir: flow123d
      browser: githubweb
      browser-url: https://github.com/flow123d/flow123d/
      skip-tag: true
triggers:
  - pollscm:
      cron: "H 2 * * *"
builders:
  - shell: |
      FLOW=/opt/flow123d/flow123d
      TOKEN=/home/builder/jenkins/static/.coveralls.yml
      FLOW_CACHE=/home/builder/git-cache/flow123d.git
      _GIT_BRANCH=master

      docker rm -f contcoverage || echo "container not running"
      docker run --privileged -di --name contcoverage -v $FLOW_CACHE:$FLOW_CACHE
      # -------------------->
      docker exec contcoverage cp $FLOW/config/config-jenkins-docker-coverage.cmake $FLOW/config.cmake

      docker exec contcoverage git clone --reference $FLOW_CACHE -b $_GIT_BRANCH https://github.com/flow123d/flow123d.git $FLOW
      docker exec contcoverage mv $FLOW/../build-$_GIT_BRANCH $FLOW
      docker exec contcoverage ln -s $FLOW/build-$_GIT_BRANCH $FLOW/../build-$_GIT_BRANCH

      docker cp $TOKEN contcoverage:$FLOW

      docker exec contcoverage make -C $FLOW all
      docker exec contcoverage make -C $FLOW/unit_tests/ all-unit-test
      docker exec contcoverage cd $FLOW && coveralls -r . -i src -e src/dealii --follow-symlinks
      # <--------------------
      docker exec stop -f contcoverage
