# ---------------------------------------------------------------------------- #
# ---------- DAILY-UPDATE ---------------------------------------------------- #
# ---------------------------------------------------------------------------- #
# Daily docker image update and reference repo update
name: Flow123d-daily-update
description: 'Daily maintenance update'
node: ci2runner
workspace: F123-ci2runner
wrappers:
  - build-name:
      name:  "daily-update #${BUILD_NUMBER}"
triggers:
  - timed: "H 1 * * *" # run this job every day at 1AM
builders:
  - shell: |
      # update reference repo
      cd /home/builder/git-cache/flow123d.git
      git branch -vv
      git log -n 20 --oneline --graph
      git fetch --all --prune

      # update images
      cd /home/builder/git-cache/
      rm -rf flow123d
      git clone --reference /home/builder/git-cache/flow123d.git https://github.com/flow123d/flow123d.git
      flow123d/bin/fterm update
      flow123d/bin/fterm build
      YES_TO_ALL=1 flow123d/bin/fterm remove-old
      docker images
      docker ps -a
