common_config:
  proc: [1, 2]
  memory_limit: 1000

test_cases:
- file: 01_source.yaml
- file: 02_unsteady.yaml
- file: 03_unsteady_nobalance.yaml
- file: 04_unsteady_LMH.yaml
- file: 05_unsteady_LMH_nobalance.yaml
