# ---------------------------------------------------------------------------- #
# ---------- PROJECT --------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
name: "Multijob project debug"
platform: ci2runner
build-type: debug
unit-dir:
  - $PLACEHOLDER_unit_list$
test-dir:
  - $PLACEHOLDER_test_list$
jobs:
  - "Flow123d-{platform}-debug-build"
  - "Flow123d-{platform}-{build-type}-unit-test-{unit-dir}"
  - "Flow123d-{platform}-{build-type}-test-{test-dir}"
  - "Flow123d-{platform}-{build-type}-make-doc"
  - "Flow123d-{platform}-{build-type}-stop-image"
  - "Flow123d-{platform}-debug-multijob"
