# ---------------------------------------------------------------------------- #
# ---------- BUILD ----------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
name: "Flow123d-{platform}-{build-type}-build"
display-name: "{build-type} / Flow123d build"
defaults: flow123d-build
builders:
  - inject:
      properties-file: prop.file
  - shell: |
      docker exec cont{build-type} make -C ${{FLOW}} -j4 all
      docker exec cont{build-type} make -C ${{FLOW}}/build_tree/unit_tests -j4 gtest_mpi_obj
