# ---------------------------------------------------------------------------- #
# ---------- CONFIGURE ------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
name: "Flow123d-{platform}-{build-type}-configure"
display-name: "{build-type} / Flow123d configure"
defaults: flow123d-build
builders:
  - inject:
      properties-file: prop.file
  - shell: |
      docker exec cont{build-type} git clone --reference /home/builder/git-cache/flow123d.git -b ${{_GIT_BRANCH}} https://github.com/flow123d/flow123d.git ${{FLOW}}
      docker exec cont{build-type} cp ${{FLOW}}/config/config-jenkins-docker-{build-type}.cmake ${{FLOW}}/config.cmake
      docker exec cont{build-type} make -C ${{FLOW}} cmake
