# ---------------------------------------------------------------------------- #
# ---------- INT-TESTS ------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
name: "Flow123d-{platform}-{build-type}-test-{test-dir}"
display-name: "{build-type} / Flow123d int-test {test-dir}"
defaults: flow123d-build
disabled: false
builders:
  - inject:
      properties-file: prop.file
  # Following is a hack how to run just serial tests in a branch which contains file 'tests/run_serial_only'.
  - shell: |
      echo  ${{RUN_INTEGRATION_TESTS}}
      if -f ${{FLOW}}/tests/run_serial_only
      then
            $(exit ${{RUN_INTEGRATION_TESTS}}) || docker exec cont{build-type} ${{FLOW}}/tests/runtest ${{FLOW}}/tests/{test-dir} -n 1 --keep-going --batch
      else
            $(exit ${{RUN_INTEGRATION_TESTS}}) || docker exec cont{build-type} ${{FLOW}}/tests/runtest ${{FLOW}}/tests/{test-dir} --keep-going --batch
      fi
