# ---------------------------------------------------------------------------- #
# ---------- INT-TESTS ------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
name: "Flow123d-{platform}-{build-type}-test-{test-dir}"
display-name: "{build-type} / Flow123d int-test {test-dir}"
defaults: flow123d-build
builders:
  - shell:
      unstable-return: 42
      command: |
        echo "SKIP_INT_TESTS  = $SKIP_INT_TESTS"
        echo "RUN_SERIAL_ONLY = $RUN_SERIAL_ONLY"

        if [[ "$SKIP_INT_TESTS" = true ]] ; then
          echo "Skipping integration tests"
          exit 42
        fi

        # Following is a hack how to run just serial tests in a branch which contains file 'tests/run_serial_only'.
        if [[ "$RUN_SERIAL_ONLY" = true ]] || [[ -f ${{FLOW}}/tests/run_serial_only ]]; then
          echo "Running serial tests only"
          docker exec cont{build-type} ${{FLOW}}/tests/runtest ${{FLOW}}/tests/{test-dir} -n 1 --keep-going
        else
          docker exec cont{build-type} ${{FLOW}}/tests/runtest ${{FLOW}}/tests/{test-dir} --keep-going
        fi

publishers:
  - archive:
      artifacts: 'docker/tests/{test-dir}/**/*.log'
      allow-empty: true
