# ---------------------------------------------------------------------------- #
# ---------- UNIT-TESTS ------------------------------------------------------ #
# ---------------------------------------------------------------------------- #
name: "Flow123d-{platform}-{build-type}-unit-test-{unit-dir}"
display-name: "{build-type} / Flow123d unit-test {unit-dir}"
defaults: flow123d-build
disabled: false
builders:
  - inject:
      properties-file: prop.file
  - shell: |
      echo  ${{RUN_UNIT_TESTS}}
      $(exit ${{RUN_UNIT_TESTS}}) || docker exec cont{build-type} make -C ${{FLOW}}/build_tree/unit_tests/{unit-dir} -k all-test
